services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    networks: [quizblitz_network]
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks: [quizblitz_network]
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks: [quizblitz_network]

volumes:
  postgres_data:

networks:
  quizblitz_network:
    driver: bridge